In [8]:
## Linear algebra

import numpy as np
### Dot product: product of two arrays
f = np.ones((4,4))
g = 3*np.ones((4,4))
### 1*4+2*5
np.sum(np.dot(f, g))


ls = [(item*3) ** 3 for item in range(int((x-x%3)/3)+1)]




NameError: name 'x' is not defined

In [29]:
a = 2*np.ones((5,5))
b = 3*np.ones((7,7))

print(np.divide(b[0:5,0:5],a))

[[1.5 1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5 1.5]]


In [ ]:
import numpy as np
import cv2
#import imutils

image = cv2.imread('image.jpeg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (5, 5), 0)
edged = cv2.Canny(gray, 75, 200)

print("STEP 1: Edge Detection")
cv2.imshow("Image", image)
cv2.imshow("Edged", edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cnts = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
cnts = sorted(cnts, key = cv2.contourArea, reverse = True)[:5]
# loop over the contours
for c in cnts:
	# approximate the contour
	peri = cv2.arcLength(c, True)
	approx = cv2.approxPolyDP(c, 0.02 * peri, True)
	# if our approximated contour has four points, then we
	# can assume that we have found our screen
	if len(approx) == 4:
		screenCnt = approx
		break
# show the contour (outline) of the piece of paper
print("STEP 2: Find contours of paper")
cv2.drawContours(image, [screenCnt], -1, (0, 255, 0), 2)
cv2.imshow("Outline", image)
cv2.waitKey(0)
cv2.destroyAllWindows()