# Lab Session : 06
## Koidala Surya Prakash
### EE18btech11026

###  Note : The linear formulations and part d are submitted in a pdf format attached along with this file.

In [2]:
import numpy as np
import cvxpy as cp


### Part a : x as variable

In [48]:
#### Data 

p = np.array([[4,6,10]]).T
s = (1/1000) *np.array([40,45,210]).T
u_t = np.array([[6000,5000,3000]]).T  ### units_per_day
n_min = 1000*np.array([[5,0,4]]).T
n_max = 1000*np.array([[10,15,8]]).T


x = cp.Variable((3,1))

n = 5*cp.multiply(x,u_t)  ### no. of units per week

### Objective 

total_profit = (n.T @ p)
obj = cp.Maximize(total_profit)

### Constraints : 

total_space = (n.T @ s)
constraints = [total_space <= 6000, n<=n_max, n>= n_min,cp.sum(x)<=1]


prob1 = cp.Problem(obj, constraints)
prob1.solve()

print('The maximum profit per week is (in thousand dollars) ', obj.value/1000)
print('\n')
print('The proportions per day are\n',x.value)


The maximum profit per week is (in thousand dollars)  145.00000001009215


The proportions per day are
 [[0.16666667]
 [0.34256653]
 [0.4907668 ]]


### Part b : y as variable

In [49]:
#### Data 

p = np.array([[4,6,10]]).T
s = (1/1000) *np.array([40,45,210]).T
time_u = np.array([[1/6000,1/5000,1/3000]]).T  ### time_per_uyit
y_miy = 1000*np.array([[5,0,4]]).T
y_max = 1000*np.array([[10,15,8]]).T


y = cp.Variable((3,1)) ### yo. of uyits per week

proportioy = (1/5)*cp.multiply(y,time_u)  ### yo. of uyits per week

### Objective 

total_profit = (y.T @ p)
obj = cp.Maximize(total_profit)

### Coystraiyts : 

total_space = (y.T @ s)
constraints = [total_space <= 6000, y<=y_max, y>= y_miy,cp.sum(proportioy)<=1]


prob2 = cp.Problem(obj, constraints)
prob2.solve()

print('The maximum profit per week is (in thousand dollars) ', obj.value/1000)
print('\n')
print('Produced units per day\n',y.value)


The maximum profit per week is (in thousand dollars)  145.00000008861494


Produced units per day
 [[5000.00001266]
 [8581.13203361]
 [7351.32078363]]


### Part c : z as variable

#### Note that z3 : total no. of hours

In [50]:
#### Data 

p = np.array([[4,6,10]]).T
s = (1/1000) *np.array([40,45,210]).T
u_t = np.array([[6000,5000,3000]]).T  ### units_per_day
n_min = 1000*np.array([[5,0,4]]).T
n_max = 1000*np.array([[10,15,8]]).T


hrs_per_prod = cp.Variable((3,1))

x = hrs_per_prod/40




n = 5*cp.multiply(x,u_t)  ### no. of units per week

### Objective 

total_profit = (n.T @ p)
obj = cp.Maximize(total_profit)

### Constraints : 

total_space = (n.T @ s)
constraints = [total_space <= 6000, n<=n_max, n>= n_min,cp.sum(x)<=1]


prob3 = cp.Problem(obj, constraints)
prob3.solve()

print('The maximum profit per week is (in thousand dollars) ', obj.value/1000)

print('\n')
print('No. of hours devoted per product per week\n',hrs_per_prod.value)

hrs_per_prod_np = np.array(hrs_per_prod.value)

z = hrs_per_prod_np
z[2][0] = hrs_per_prod_np[0][0]+hrs_per_prod_np[1][0]+hrs_per_prod_np[2][0]

print('\n')
print('z1 = (hrs for ipod per week) ',z[0][0])
print('z2 = (hrs for iphone per week)',z[1][0])
print('z3 = (total working hrs)',z[2][0])

The maximum profit per week is (in thousand dollars)  145.00000000552254


No. of hours devoted per product per week
 [[ 6.66666667]
 [13.44402471]
 [19.88930862]]


z1 = (hrs for ipod per week)  6.666666668487532
z2 = (hrs for iphone per week) 13.444024711311403
z3 = (total working hrs) 40.00000000183685
