In [6]:
import numpy as np
import random

In [17]:
'''
Representation of a Tic Tac Toe board



agent_b : bit representation of the agent 

agent: 1, opponent : 2
'''


class TicTacToe(object):
    def __init__(self):
        self.state = 0  ### base state with all empty
        self.b2sym = {'0': "-", '1':"X", '2': "O"}
        self.free_actions = {0,1,2,3,4,5,6,7,8}
        
        self.reward = 0
        self.done = 0
        
        self.win_count = [0,0,0]## Draws , X wins , O wins 
        
    def reset(self):
        self.state = 0  ### base state with all empty
        self.b2sym = {'0': "-", '1':"X", '2': "O"}
        self.free_actions = {0,1,2,3,4,5,6,7,8}
        self.reward = 0
        self.done = 0
        self.first_move = random.choice([1,2])
        
        
    def check_valid(self,action):
        if(action in self.free_actions):
            return True
        return False
    ################# Utilities for check status #############
    
    def check_row(self, row_no):
        if(self.state_b3[(3*row_no) + 0] != '0' 
           and (self.state_b3[(3*row_no) + 0] == self.state_b3[(3*row_no) + 1])
           and (self.state_b3[(3*row_no) + 1] == self.state_b3[(3*row_no) + 2]) ) :
            
            return int(self.state_b3[(3*row_no) + 0])
        return 0
    
    def check_col(self, col_no):
        if(self.state_b3[col_no + (3*0)] != '0' 
           and (self.state_b3[col_no + (3*0)] == self.state_b3[col_no + (3*1)])
           and (self.state_b3[col_no + (3*1)] == self.state_b3[col_no + (3*2)]) ) :

            return int(self.state_b3[col_no + (3*0)])
        return 0
    
    def check_diag(self):
        if(self.state_b3[0]!='0'
          and (self.state_b3[0]==self.state_b3[4])
          and (self.state_b3[4]==self.state_b3[8])):
            return int(self.state_b3[0])
        return 0
    
    def check_antidiag(self):
        if(self.state_b3[2]!='0'
          and (self.state_b3[2]==self.state_b3[4])
          and (self.state_b3[4]==self.state_b3[6])):

            return int(self.state_b3[2])
        return 0
    #############################################################    


    def check_status(self):
        '''
        return 0 if game is live
        1 if 1 wins
        2 if 2 wins
        -1 if drawn
        '''
        if(len(self.free_actions) >=5): #game is live if only 4 or less actions were taken
            return 0 
        else:
            for i in range(3): #### Checking all rows
                if(self.check_row(i)!=0):
                    return self.check_row(i)

                
            for j in range(3): #### Checking for cols
                if(self.check_col(j)!=0):
                    return self.check_col(j)

            
            if(self.check_diag()!=0): #### Checking for diag
                return self.check_diag()

            
            if(self.check_antidiag()!=0): ### Checking for antidiag
                return self.check_antidiag()
            
           
        if(len(self.free_actions) == 0): 
            return -1 ### game drawn
        return 0 ### The game is still live if none satisfy
   
    ###################### Utility for act
    def base3_rep(self,x):
        '''
        returns base rep in reverse formate
        567 := 000210000 --> 000012000
        '''
        bit_rep = np.base_repr(x, 3)
        ans = "0"*(9-len(bit_rep)) + bit_rep
        ans = ans[::-1]## reversed.
        return ans
    #######################################################


    def act(self,agent_b,action, display_every = False, display_final = False):
        #self.reward = 0
        if(self.done ==1):
            #print("GAME OVER !!")
            return [self.state, self.reward, self.done]
        
        ### checking will be done by checking in self.free actions
        self.state  = self.state + agent_b*(pow(3, action))
        self.state_b3 = self.base3_rep(self.state)
        self.game_status = self.check_status()
        
        if(display_every):
            self.print_board()
            print("Status : ",self.game_status)
            
        if(self.game_status != 0):
            if(self.game_status ==1):
                #print("Agent Wins !!!")
                self.win_count[1] = self.win_count[1] + 1 
                self.reward = +10
                
            elif(self.game_status==2):
                #print("Opponent Wins :( ")
                self.win_count[2] = self.win_count[2] + 1
                self.reward = -10
            elif(self.game_status == -1):
                #print("Game Drawn")
                self.reward = 1
                self.win_count[0] = self.win_count[0] + 1
            self.done = 1
            
            if(display_final):
                self.print_board()
                print("Status : ",self.game_status)
        
            
        return [self.state, self.reward, self.done, self.win_count]
            
        
    def print_board(self, state = None): ### printing the board
        '''
        Takes the number representation of the state --> converts to bit representation of base 3--> prints it
        '''
    
        for i in range(9):
            if(i%3==0) :
                print("");
            print(self.b2sym[self.state_b3[i]], end = " ")
        print("")
        
    def print_board_given_state(self, state = None): ### printing the board
        '''
        Takes the number representation of the state --> converts to bit representation of base 3--> prints it
        '''
        
        if(state !=None):
            state_b3 = self.base3_rep(state)
        for i in range(9):
            if(i%3==0) :
                print("");
            print(self.b2sym[state_b3[i]], end = " ")
        print("")
        
        
    #############################################################################################3
    ##############  DEVELOPING OPPONENTS FOR Q LEARNING #########################################3
    ##############################################################################################
    

    

            
        
        
        

In [16]:
#### Trained on a safe agent 
TTT = TicTacToe()
A1 = A_rand
A2 = random_agent(2, "A2")

for e in range(1):
    print("######")
    print("EPISODE: ", e)
    print("######") 
    
    TTT.reset()
    player = random.sample([A1, A2], 1)[0]
    while(TTT.done==0):
        action = player.get_action(TTT)
        TTT.free_actions.remove(action)
        after_action_state = (TTT.act(player.get_player_id(),action,display_every = True))
        print(after_action_state)
        if(player ==A1):
            player = A2
        elif(player == A2):
            player = A1
    if(TTT.done):
        print(after_action_state)

######
EPISODE:  0
######

- - - 
X - - 
- - - 
Status :  0
[27, 0, 0, [0, 0, 0]]

- - - 
X O - 
- - - 
Status :  0
[189, 0, 0, [0, 0, 0]]

- - - 
X O X 
- - - 
Status :  0
[432, 0, 0, [0, 0, 0]]

- - - 
X O X 
- O - 
Status :  0
[4806, 0, 0, [0, 0, 0]]

- X - 
X O X 
- O - 
Status :  0
[4809, 0, 0, [0, 0, 0]]

- X - 
X O X 
- O O 
Status :  0
[17931, 0, 0, [0, 0, 0]]

X X - 
X O X 
- O O 
Status :  0
[17932, 0, 0, [0, 0, 0]]

X X O 
X O X 
- O O 
Status :  0
[17950, 0, 0, [0, 0, 0]]

X X O 
X O X 
X O O 
Status :  1
[18679, 10, 1, [0, 1, 0]]
[18679, 10, 1, [0, 1, 0]]


In [18]:
          
class Player :
    def __init__(self, player_id, player_name = None):
        self.player_id = player_id ### either 1 : X or 2: O
        self.player_name =  player_name
        
class HumanPlayer(Player):
    pass


class ComputerPlayer(Player):
    
    def __init__(self,player_id, player_name):
        Player.__init__(self,player_id, player_name)
    def get_player_id(self):
        return self.player_id
    
    def get_player_name(self):
        return self.player_name
    
    def get_action(self, TTT_obj):
        return self.policy(TTT_obj)

class random_agent(ComputerPlayer,TicTacToe):

    def __init__ (self, player_id, player_name):
        ComputerPlayer.__init__(self,player_id, player_name)
    
    def policy(self, TTT_obj):
        action = random.sample(TTT_obj.free_actions,1)[0]
        return action
    
class safe_agent(ComputerPlayer, TicTacToe):
    def __init__ (self, player_id, player_name):
        ComputerPlayer.__init__(self,player_id, player_name)
        
    ########## Utilities for ..policy

    def helper(self,a, player_id):

        if(player_id == 2):
            if(a==2) :return 1
            elif(a==1): return -1
            else: return 0
            
        elif(player_id == 1):
            if(a==2): return -1
            elif(a==1): return +1
            else: return 0
    
    def state2arr(self,TTT_obj, player_id):### to convert state in int form to array with -1(X), 0(.), 1(O)
        base_rep = self.base3_rep(TTT_obj.state)
        arr = np.array([[ self.helper(int(base_rep[3*i + j]), player_id) for j in range(3)]for i in range(3)])
        
        return arr
    

    def return_set_of_sums(self,p, state_arr): ## pos poistion of free moves {0,3, 7}
        ### returns the set of sums of row_sum, col_sum, diag_sum, anti_diag_sum
        ###if not possible to compute diag or anti diag returns -1

        i,j = int(p/3), int(p%3)
        row_sum = np.sum(state_arr[i,:])
        col_sum  = np.sum(state_arr[:,j])
        diag_sum = -1
        anti_diag_sum = -1


        if(p in {0,4,8}): ## possible to calculate diag sum
            diag_sum = state_arr[0][0] + state_arr[1][1] + state_arr[2][2]


        if(p in {2,4,6}):##3 possible to calculate antidiag sum
            anti_diag_sum =  state_arr[2][0] + state_arr[1][1] + state_arr[0][2]
        return {row_sum, col_sum, diag_sum , anti_diag_sum}

        
    def policy(self, TTT_obj):
        win_action_set = set()
        block_action_set = set()
        win_flag = False
        block_flag = False
        
        
        ##### Remember the safe agent can only place an 'O' i.e a number 1 and 'X' represent -1 in state_arr
        ### If sum of row /col/diag/antidiag ==+2 : win case
        ### if ==-2 block case
        state_arr = self.state2arr(TTT_obj, player_id =self.player_id ) ## create arr wrt player  
        #print(state_arr)
        for p in TTT_obj.free_actions:
            action_set_of_sums = self.return_set_of_sums(p, state_arr)### possible sums other than p (row, col, diag,antidiag)
            if(2 in action_set_of_sums):
                win_action_set.add(p) ## win condition
                win_flag = True
            elif(-2 in action_set_of_sums):
                block_action_set.add(p)
                block_flag = True
            
        if(win_flag):
            action = random.sample(win_action_set,1)[0]  ### win condition
            #print("I chose win")
        elif(block_flag):
            action = random.sample(block_action_set,1)[0] ### block condition
            #print("I chose block")
        else:
            action =random.sample(TTT_obj.free_actions,1)[0] ### random condition
            #print("I chose rand")
        return action
                
class Q_agent(TicTacToe):
    def __init__(self, player_id, player_name):
        self.player_id=  player_id
        self.eps= 0.2
        self.gamma = 1 ## discount
        self.alpha = 0.01
        self.Q_val = {}
        
    def get_player_id(self):
        return self.player_id
        
    def eps_greedy(self, TTT_obj):
        t = random.random()
        if(t < self.eps):
            return random.sample(TTT_obj.free_actions,1)[0]
        else:
            return self.get_action(TTT_obj)### full greedy
    
    def get_action(self, TTT_obj):
        s = TTT_obj.state
        max_val = max([self.Q(s,a) for a in TTT_obj.free_actions])
        max_actions = [a for a in TTT_obj.free_actions if self.Q(s,a)==max_val ]
        return random.choice(max_actions)
    
    def Q(self, s, a):
        if(s,a) not in self.Q_val:
            self.Q_val[(s,a)] = 0
        return self.Q_val[(s,a)]
    
    def Q_update(self, curr_s, curr_a, r, nxt_s, nxt_actions):
        if(len(nxt_actions) == 0):
            max_val = 0
        else: 
            max_val = max([self.Q(nxt_s, a) for a in nxt_actions])
        self.Q_val[(curr_s,curr_a)] = (1-self.alpha)*(self.Q(curr_s,curr_a)) + self.alpha*(r + self.gamma*max_val)
            
    

In [364]:
'''
class Q_agent( TicTacToe):
    def __init__ (self, player_id, player_name):
        #ComputerPlayer.__init__(self,player_id, player_name)
        self.Q_val = np.zeros((pow(3,9), 9)) ### state action space is a matrix init to zeros
        self.eps = 0 ### full -greedy
        self.alpha = 0.01 ## lr
        self.gamma = 1 ## discount factor
        
        self.player_id = player_id
        self.player_name = player_name
        
    def get_player_id(self):
        return self.player_id

    def get_player_name(self):
        return self.player_name
        

        
    def policy(self, TTT_obj):
        state = TTT_obj.state
        max_Q_sa = max([self.Q_val[state][a] for a in TTT_obj.free_actions ] )
        arg_max_indices = [a for a in TTT_obj.free_actions if self.Q_val[state][a]== max_Q_sa ]
        action = random.sample(arg_max_indices, 1)[0] ### if multiple actions have max Q
        return action

    def get_action(self,TTT_obj):
        t = random.random() 
        if(t < self.eps):
            action = random.sample(TTT_obj.free_actions,1)[0]
        else:
            action  = self.policy(TTT_obj)
        return action


    def Q_update(self, s, a, r, ns, n_actions):### s--> current state, a--> action, r--> reward, ns-->next state, n_actions--> next actions
        '''
        if(len(n_actions)==0):
            Q_max_ns_na = 0
        else : 
        '''
        if(len(n_actions) == 0):
            print(ns)
        Q_max_ns_na = max([self.Q_val[ns][na] for na in n_actions ] )
        self.Q_val[s][a] = self.Q_val[s][a] + self.alpha*(r + (self.gamma*(Q_max_ns_na)) - self.Q_val[s][a])


'''


IndentationError: unexpected indent (<ipython-input-364-bff2c29a6d6e>, line 39)

In [10]:
def train_Q_agent(agent, opponents, TTT_obj, epochs =  10, test_every = 2, test_episodes = 10):
    for e in range(epochs):
        TTT_obj.reset()
        opponent = random.sample(opponents, 1)[0]
        player = random.sample([agent, opponent], 1)[0]
        #print(str(player.get_player_id) + " will make the first move ..")
        
        if(player.get_player_id == 2): ### An opponent takes the first turn
            action = player.get_action(TTT_obj)
            TTT_obj.free_actions.remove(action)
            TTT_obj.act(player.get_player_id(),action,display_every = False)
        
        while(TTT_obj.done ==0):
            
            player = agent ### agent play
            curr_state = TTT_obj.state
            curr_action = player.eps_greedy(TTT_obj)
            TTT_obj.free_actions.remove(curr_action)
            
            
            [ns,r, _, _] = (TTT_obj.act(player.get_player_id(),curr_action,display_every = False))
            
            if(TTT_obj.done):
                pass
            else:### if did not reach an end state ask the opponent to move
                player = opponent
                action = player.get_action(TTT_obj)
                TTT_obj.free_actions.remove(action)
                [ns,r, _, _] = TTT_obj.act(player.get_player_id(),action,display_every = False)
            

            agent.Q_update(curr_state, curr_action, r, ns, TTT_obj.free_actions)
            
        if(e%test_every ==0):
            print('---------------------------------------------------')
            print('Epoch %d'%e)
            test_Q_agent(agent, opponents, TTT_obj, test_episodes)
            print('---------------------------------------------------')
            
                
            
def test_Q_agent(agent, opponents, TTT_obj, test_episodes ):
    TTT_obj.win_count = [0,0,0]  ### resetting win count to 0
    for e in range(test_episodes):
        TTT_obj.reset()
        opponent = random.sample(opponents, 1)[0]
        player = random.sample([agent, opponent], 1)[0]
        
        while(TTT_obj.done ==0):
            curr_state = TTT_obj.state
            action = player.get_action(TTT_obj)
            TTT_obj.free_actions.remove(action)
            
            after_action_state = (TTT_obj.act(player.get_player_id(),action))
            
            if(player.get_player_id() == 1):
                player = opponent
            elif(player.get_player_id() == 2): 
                player = agent
    #print(after_action_state)
    print('For %d test episodes ==>  Draws :%d  Wins: %d Losses :%d '%(test_episodes, after_action_state[3][0],after_action_state[3][1],after_action_state[3][2] ) )
        
        
        

In [64]:
A_rand = Q_agent(1, "A")

print(A_rand.Q_val)
A_rand.Q(1,1)
print(A_rand.Q_val)

{}
{(1, 1): 0}


In [11]:
##### Trained on random agent .........

TTT = TicTacToe()
A_rand = Q_agent(1, "A")
print(A_rand.Q_val)
opp1 = random_agent(2, "O1")
train_Q_agent(agent = A_rand, opponents = [opp1], TTT_obj = TTT, epochs =  10000, test_every = 200, test_episodes = 100)
print(A_rand.Q_val)


TTT_A_rand_vs_rand = TicTacToe()  
A1 = A_rand
A2 = random_agent(2, "A2")
test_Q_agent(agent = A1, opponents = [A2], TTT_obj = TTT_A_rand_vs_rand, test_episodes = 100 )

{}
---------------------------------------------------
Epoch 0
For 100 test episodes ==>  Draws :10  Wins: 58 Losses :32 
---------------------------------------------------
---------------------------------------------------
Epoch 200
For 100 test episodes ==>  Draws :9  Wins: 38 Losses :53 
---------------------------------------------------
---------------------------------------------------
Epoch 400
For 100 test episodes ==>  Draws :7  Wins: 50 Losses :43 
---------------------------------------------------
---------------------------------------------------
Epoch 600
For 100 test episodes ==>  Draws :5  Wins: 60 Losses :35 
---------------------------------------------------
---------------------------------------------------
Epoch 800
For 100 test episodes ==>  Draws :3  Wins: 64 Losses :33 
---------------------------------------------------
---------------------------------------------------
Epoch 1000
For 100 test episodes ==>  Draws :12  Wins: 61 Losses :27 
----------------

In [67]:
for key,value in A_rand.Q_val.items():
    if(value >0):
        print(key,value)

(0, 8) 5.0908088703280665
(17625, 5) 0.1
(8708, 7) 1.8453117633195457
(12183, 4) 0.001
(12194, 4) 1.902721317787415
(12218, 4) 0.1
(18678, 0) 0.1
(11837, 5) 3.17445404989613
(5598, 4) 0.1
(489, 7) 0.001
(12974, 3) 0.445626686715373
(6723, 2) 5.613388420764659
(7041, 6) 0.002940399
(746, 4) 0.1
(12920, 4) 1.9128839464185088
(6579, 5) 1.5254296487519416
(6824, 1) 0.5127009342613743
(7827, 0) 0.1
(6567, 5) 7.145459474846195
(7433, 2) 0.1
(12495, 3) 2.979446371808005
(12792, 0) 0.8648275251635908
(10935, 2) 5.5674553992635065
(12282, 0) 0.199
(15790, 6) 0.03
(14275, 3) 0.1
(11196, 3) 1.4103306031653668
(11225, 1) 0.7291312537904021
(12116, 1) 0.3408453848516121
(4065, 0) 0.001
(4120, 8) 0.199
(11871, 5) 0.0003
(7361, 7) 0.1
(8424, 2) 0.1
(14974, 7) 0.03
(7047, 4) 7.042819815401909
(7851, 7) 0.1
(17086, 4) 0.1
(6786, 5) 9.877477673791343
(11889, 5) 0.1
(9407, 6) 4.417338614521361
(10950, 5) 8.788311836429484
(17214, 0) 0.03
(17890, 6) 0.1
(10608, 0) 0.490099501
(10942, 4) 0.1
(6615, 2) 6.89

In [51]:
##### Trained on safe agent .........

TTT = TicTacToe()
A_safe = Q_agent(1, "A")
opp2 = safe_agent(2, "O2")
train_Q_agent(agent = A_safe, opponents = [opp2], TTT_obj = TTT, epochs =  10000, test_every = 200, test_episodes = 100)


TTT_A_rand_vs_safe = TicTacToe()  
A1 = A_safe
A2 = safe_agent(2, "A2")
test_Q_agent(agent = A1, opponents = [A2], TTT_obj = TTT_A_rand_vs_safe, test_episodes = 100 )

---------------------------------------------------
Epoch 0
For 100 test episodes ==>  Draws :17  Wins: 5 Losses :78 
---------------------------------------------------
---------------------------------------------------
Epoch 200
For 100 test episodes ==>  Draws :20  Wins: 4 Losses :76 
---------------------------------------------------
---------------------------------------------------
Epoch 400
For 100 test episodes ==>  Draws :27  Wins: 12 Losses :61 
---------------------------------------------------
---------------------------------------------------
Epoch 600
For 100 test episodes ==>  Draws :37  Wins: 10 Losses :53 
---------------------------------------------------
---------------------------------------------------
Epoch 800
For 100 test episodes ==>  Draws :34  Wins: 18 Losses :48 
---------------------------------------------------
---------------------------------------------------
Epoch 1000
For 100 test episodes ==>  Draws :37  Wins: 9 Losses :54 
------------------

---------------------------------------------------
Epoch 9600
For 100 test episodes ==>  Draws :44  Wins: 9 Losses :47 
---------------------------------------------------
---------------------------------------------------
Epoch 9800
For 100 test episodes ==>  Draws :38  Wins: 16 Losses :46 
---------------------------------------------------
For 100 test episodes ==>  Draws :36  Wins: 15 Losses :49 


In [68]:
##### Trained on both agent .........

TTT = TicTacToe()
A_both = Q_agent(1, "A")
print(A_both.Q_val)
opp1 = random_agent(2,"O1")
opp2 = safe_agent(2, "O2")
train_Q_agent(agent = A_both, opponents = [opp1, opp2], TTT_obj = TTT, epochs =  10000, test_every = 200, test_episodes = 100)
print(A_both.Q_val)

TTT_A_rand_vs_safe_rand = TicTacToe()  
A1 = A_both
A2 = safe_agent(2, "A2")
A3 = random_agent(2, "A2")
test_Q_agent(agent = A1, opponents = [A2, A3], TTT_obj = TTT_A_rand_vs_safe_rand, test_episodes = 100 )

{}
---------------------------------------------------
Epoch 0
For 100 test episodes ==>  Draws :13  Wins: 24 Losses :63 
---------------------------------------------------
---------------------------------------------------
Epoch 200
For 100 test episodes ==>  Draws :16  Wins: 15 Losses :69 
---------------------------------------------------
---------------------------------------------------
Epoch 400
For 100 test episodes ==>  Draws :17  Wins: 22 Losses :61 
---------------------------------------------------
---------------------------------------------------
Epoch 600
For 100 test episodes ==>  Draws :18  Wins: 30 Losses :52 
---------------------------------------------------
---------------------------------------------------
Epoch 800
For 100 test episodes ==>  Draws :26  Wins: 34 Losses :40 
---------------------------------------------------
---------------------------------------------------
Epoch 1000
For 100 test episodes ==>  Draws :19  Wins: 32 Losses :49 
------------

---------------------------------------------------
Epoch 9800
For 100 test episodes ==>  Draws :31  Wins: 29 Losses :40 
---------------------------------------------------
{(0, 0): 0.0, (0, 1): 0.0, (0, 2): 0.0, (0, 3): 2.6577814626654503, (0, 4): 0.0, (0, 5): 0.0, (0, 6): 0.0, (0, 7): 0.0, (0, 8): 0.0, (15309, 0): 0.0, (15309, 1): 0.0, (15309, 2): 0, (15309, 3): 0.0, (15309, 4): 0.0, (15309, 5): 0.0, (15309, 6): 0.0, (15876, 0): 0, (15876, 1): 0, (15876, 2): 0, (15876, 3): 0, (15876, 6): 0.0, (16611, 0): 0, (16611, 2): 0, (16611, 3): 0.0, (16640, 2): 0.3940399, (162, 0): 0, (162, 1): 0, (162, 2): 0, (162, 3): 0, (162, 5): 0, (162, 6): 0, (162, 7): 0, (162, 8): 0, (897, 0): 0, (897, 2): 0, (897, 3): 0, (897, 5): 0, (897, 7): 0, (897, 8): 0, (2, 1): 0, (2, 2): 0, (2, 3): 0, (2, 4): 0, (2, 5): 0, (2, 6): 0, (2, 7): 0, (2, 8): 0, (6617, 1): 0, (6617, 2): 0, (6617, 4): 0, (6617, 5): 0, (6617, 6): 0, (6617, 7): 0, (4455, 0): 0, (4455, 1): 0.0, (4455, 2): 0, (4455, 3): 0, (4455, 5): 0, (44

In [38]:
#### Trained on a safe agent 
TTT = TicTacToe()
A1 = A_rand
A2 = random_agent(2, "A2")

for e in range(100):
    print("######")
    print("EPISODE: ", e)
    print("######") 
    
    TTT.reset()
    player = random.sample([A1, A2], 1)[0]
    while(TTT.done==0):
        action = player.get_action(TTT)
        TTT.free_actions.remove(action)
        after_action_state = (TTT.act(player.get_player_id(),action))
        
        if(player ==A1):
            player = A2
        elif(player == A2):
            player = A1
    if(TTT.done):
        print(after_action_state)
        
TTT_A_rand_vs_rand = TicTacToe()  
A1 = A_rand
A2 = random_agent(2, "A2")
test_Q_agent(agent = A1, opponents = [A2], TTT_obj = TTT_A_rand_vs_rand, test_episodes = 100 )

######
EPISODE:  0
######
[18358, 10, 1, [0, 1, 0]]
######
EPISODE:  1
######
[17847, 10, 1, [0, 2, 0]]
######
EPISODE:  2
######
[17847, 10, 1, [0, 3, 0]]
######
EPISODE:  3
######
[8487, 10, 1, [0, 4, 0]]
######
EPISODE:  4
######
[9956, 10, 1, [0, 5, 0]]
######
EPISODE:  5
######
[8155, 10, 1, [0, 6, 0]]
######
EPISODE:  6
######
[11717, -10, 1, [0, 6, 1]]
######
EPISODE:  7
######
[12281, 5, 1, [1, 6, 1]]
######
EPISODE:  8
######
[5272, -10, 1, [1, 6, 2]]
######
EPISODE:  9
######
[375, 10, 1, [1, 7, 2]]
######
EPISODE:  10
######
[13028, -10, 1, [1, 7, 3]]
######
EPISODE:  11
######
[11294, 10, 1, [1, 8, 3]]
######
EPISODE:  12
######
[13491, 10, 1, [1, 9, 3]]
######
EPISODE:  13
######
[12864, 10, 1, [1, 10, 3]]
######
EPISODE:  14
######
[13475, 10, 1, [1, 11, 3]]
######
EPISODE:  15
######
[1832, 10, 1, [1, 12, 3]]
######
EPISODE:  16
######
[12746, 10, 1, [1, 13, 3]]
######
EPISODE:  17
######
[11328, 10, 1, [1, 14, 3]]
######
EPISODE:  18
######
[8176, 10, 1, [1, 15, 3]]
###

In [34]:
arr = np.array([[1,2,3],[3,2,3], [5, 3, 6]])
print(arr[1][:])

maxi = np.amax(arr[1][:])
print( (np.where(arr[1][:] == maxi))[0] )
#print ((random.sample(set(np.where(arr[1][:] == maxi))[0],1) )[0])


lis = list(np.where(arr[1][:] == maxi)[0])

print( random.sample(lis ,1)[0] )

[3 2 3]
[0 2]
0


In [ ]:
TTT = TicTacToe()
A1 = random_agent(1, "A1")
A2 = random_agent(2, "A2")


###  Q -learning

In [3]:
def base3_rep(x):
    '''
    returns base rep in reverse formate
    567 := 000210000 --> 000012000
    '''
    bit_rep = np.base_repr(x, 3)
    ans = "0"*(9-len(bit_rep)) + bit_rep
    ans = ans[::-1]## reversed.
    return ans

def state2arr(TTT_obj):
    bit_rep = base3_rep(TTT_obj.state)
    arr = np.array([[ int(bit_rep[3*i + j]) for j in range(3)]for i in range(3)])
    return arr

TTT = TicTacToe()
TTT.state = 567
print(state2arr(TTT))
np.sum(state2arr(TTT)[1,:])


#@staticmethod
def return_set_of_sums(p, state_arr): ## pos poistion of free moves {0,3, 7}
    ### returns the set of sums of row_sum, col_sum, diag_sum, anti_diag_sum
    ###if not possible to compute diag or anti diag returns -1

    i,j = int(p/3), int(p%3)
    row_sum = np.sum(state_arr[i,:])
    col_sum  = np.sum(state_arr[:,j])
    diag_sum = -1
    anti_diag_sum = -1
    
    
    if(p in {0,4,8}): ## possible to calculate diag sum
        diag_sum = state_arr[0][0] + state_arr[1][1] + state_arr[2][2]

        
    if(p in {2,4,6}):##3 possible to calculate antidiag sum
        anti_diag_sum =  state_arr[2][0] + state_arr[1][1] + state_arr[2][0]
    return {row_sum, col_sum, diag_sum , anti_diag_sum}
        
    
pos = 0
arr = np.array([[0,1,2],[1,0,1],[2,1,2]])
print(arr)
print(return_set_of_sums(pos,arr))

[[0 0 0]
 [0 1 2]
 [0 0 0]]
[[0 1 2]
 [1 0 1]
 [2 1 2]]
{2, 3, -1}


In [396]:
1 in {0,6,2}

False

In [19]:
a = {1,2,3,4,5}
for i in a:
    print(i)

1
2
3
4
5


In [239]:
TTT = TicTacToe()
player = Player(TTT)
comp_player = ComputerPlayer(player)

RA1 = random_agent(comp_player)
for e in range(10):
    print("######")
    print("EPISODE: ", e)
    print("######") 
    
    TTT.reset()
    player = 2
    while(TTT.done==0):
        action = random.sample(TTT.free_actions,1)[0]
        TTT.free_actions.remove(action)
        TTT.act(player,action)
        
        if(player ==1):
            player = 2
        else:
            player = 1

######
EPISODE:  0
######
Agent Wins !!!

O X O 
O O - 
X X X 
Status :  1
######
EPISODE:  1
######
Opponent Wins :( 

O O X 
O X O 
O X X 
Status :  2
######
EPISODE:  2
######
Opponent Wins :( 

X - O 
- O X 
O O X 
Status :  2
######
EPISODE:  3
######
Agent Wins !!!

O - O 
- O - 
X X X 
Status :  1
######
EPISODE:  4
######
Agent Wins !!!

O O X 
O - X 
X O X 
Status :  1
######
EPISODE:  5
######
Opponent Wins :( 

X - - 
O O O 
X - - 
Status :  2
######
EPISODE:  6
######
Agent Wins !!!

O X O 
O - O 
X X X 
Status :  1
######
EPISODE:  7
######
Opponent Wins :( 

X X O 
- - O 
- - O 
Status :  2
######
EPISODE:  8
######
Opponent Wins :( 

X X O 
O O X 
O X O 
Status :  2
######
EPISODE:  9
######
Agent Wins !!!

X X - 
O X O 
O X O 
Status :  1


In [202]:
TTT = TicTacToe()

agent,action = 1,0
TTT.free_actions.remove(action)
TTT.act(agent,action)

agent,action = 2,4
TTT.free_actions.remove(action)
TTT.act(agent,action)

agent,action = 1,1
TTT.free_actions.remove(action)
TTT.act(agent,action)

agent,action = 2,2
TTT.free_actions.remove(action)
TTT.act(agent,action)

agent,action = 1,3
TTT.free_actions.remove(action)
TTT.act(agent,action)

agent,action = 2,6
TTT.free_actions.remove(action)
TTT.act(agent,action)



X - - 
- - - 
- - - 
Status :  0

X - - 
- O - 
- - - 
Status :  0

X X - 
- O - 
- - - 
Status :  0

X X O 
- O - 
- - - 
Status :  0

X X O 
X O - 
- - - 
Status :  0

X X O 
X O - 
O - - 
Status :  2
Opponent Wins :( 


[1669, -10, 1]

In [205]:
    ################# Utilities for check status #############
    
    def check_row(self, row_no):
        if(self.state_b3[(3*row_no) + 0] != '0' 
           and (self.state_b3[(3*row_no) + 0] == self.state_b3[(3*row_no) + 1])
           and (self.state_b3[(3*row_no) + 1] == self.state_b3[(3*row_no) + 2]) ) :
            
            return int(self.state_b3[(3*row_no) + 0])
        return 0
    
    def check_col(self, col_no):
        if(self.state_b3[col_no + (3*0)] != '0' 
           and (self.state_b3[col_no + (3*0)] == self.state_b3[col_no + (3*1)])
           and (self.state_b3[col_no + (3*1)] == self.state_b3[col_no + (3*2)]) ) :

            return int(self.state_b3[col_no + (3*0)])
        return 0
    
    def check_diag(self):
        if(self.state_b3[0]!='0'
          and (self.state_b3[0]==self.state_b3[4])
          and (self.state_b3[4]==self.state_b3[8])):
            
            return int(self.state_b3[0])
        return 0
    
    def check_antidiag(self):
        if(self.state_b3[2]!='0'
          and (self.state_b3[2]==self.state_b3[4])
          and (self.state_b3[4]==self.state_b3[6])):

            return int(self.state_b3[2])
        return 0
    #############################################################

In [41]:
np.base_repr(567, base = 3) 


def base3_rep(x):
    bit_rep = np.base_repr(x, 3)
    ans = "0"*(9-len(bit_rep)) + bit_rep
    return ans


   

In [43]:
x = (base_3_rep(567))
print(x)



for i , bit in enumerate(x):
    i = 8-i
    
    
for i in range(len(x)-1,-1,-1):
    print(x[i], end = " ")
    
    if(i%3==0):
        print('\n')
        


000210000
0 0 0 

0 1 2 

0 0 0 



In [31]:
temp = {0: "-", 1:"X", 2: "O"}
print(temp[1])

X
